"""Initial migration

Revision ID: 9c3b4b139d06
Revises: 
Create Date: 2023-05-28 23:43:34.441792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3b4b139d06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balances', ['id'])
    op.create_unique_constraint(None, 'organizations', ['id'])
    op.create_unique_constraint(None, 'payments', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'balances', type_='unique')
    # ### end Alembic commands ###
